using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameManager : MonoBehaviour
{
    //GameManagerを常に一つ
    public static GameManager Instance {  get; private set; }

    //ゲーム状態
    public enum GameState
    {
        MainMenu,
        Playing,
        Paused,
        GameOver,
    }
    // 現在のゲーム状態を保持
    public GameState state { get; private set; }
    private void Awake()
    {
        if(Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            //存在しているなら破棄する
            Destroy(gameObject);
        }
        
    }
    // Update is called once per frame
    void Update()
    {
        
    }
}
